name: Actions Workflows

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Simple JS Actions
        id: greet
        uses: actions/hello-world-javascript-action@v1.1
        with: 
          who-to-greet: ilhan
      - name: Log Greating Time 
        run: echo "${{ steps.greet.outputs.time }}"
