name: Container
on: push

jobs: 
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: node:18.8.0-alpine3.15
    steps:
      - name: log node version
        run: |
          node -v
          cat /etc/os-release
    